# Generated by Django 4.1.3 on 2024-10-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevolucionCompra',
        ),
    ]
