# Generated by Django 4.1.3 on 2024-10-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_delete_devolucioncompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
