# Generated by Django 4.1.3 on 2024-11-03 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_detallecompra_costo_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='tipo_compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.tipocompra'),
            preserve_default=False,
        ),
    ]
