# Generated by Django 4.1.3 on 2024-10-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_kardex_costo_unitario_kardex_precio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='total_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
