# Generated by Django 4.1.3 on 2024-11-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0003_kardex_total_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
