# Generated by Django 4.1.3 on 2024-11-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaventa',
            name='id',
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='numero_factura',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
