# Generated by Django 4.1.3 on 2024-11-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_direccion_proveedor_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoCompra',
            new_name='TipoProveedor',
        ),
    ]
