# Generated by Django 4.1.3 on 2024-10-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_id_alter_estadoproducto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='costo_unitario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
    ]
